# Generated by Django 5.0.4 on 2024-04-29 08:50

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('I', 'I Anfänger'), ('II', 'II Fortgeschritten'), ('III', 'I Profi')], max_length=3)),
                ('requirements', models.CharField(max_length=20)),
                ('description_short', models.CharField(max_length=20)),
                ('content_list', models.TextField()),
                ('methods', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('dates', models.CharField(max_length=20)),
                ('duration', models.DurationField(default='2 Hours')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilog_backend.courseinfo')),
                ('atendees', models.ManyToManyField(blank=True, related_name='attends', to='digilog_backend.user')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilog_backend.user')),
            ],
        ),
    ]
