# Generated by Django 5.0.4 on 2024-04-22 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('occupation', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(verbose_name='2 hours')),
                ('status', models.CharField(choices=[('NM', 'Normal'), ('CL', 'Cancled')], default='NM', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilog_backend.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='atendees',
            field=models.ManyToManyField(blank=True, related_name='attends', to='digilog_backend.person'),
        ),
        migrations.AddField(
            model_name='course',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digilog_backend.person'),
        ),
    ]
