# Generated by Django 5.0.4 on 2024-04-18 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('atendees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attends', to='digilog_backend.person')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='digilog_backend.person')),
            ],
        ),
    ]
