# Generated by Django 5.0.4 on 2024-04-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digilog_backend', '0002_remove_event_atendees_alter_event_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='atendees',
            field=models.ManyToManyField(blank=True, related_name='attends', to='digilog_backend.person'),
        ),
    ]
